name: FasterTreeChopping
main: me.bukkit.fastergameplay.FasterTreeChopping
version: 1.0
description: Naturally chops tree upon first chop
commands:
   pitchup:
      description: setting pitch
      usage: /<command>
   pitchdown:
      description: setting pitch
      usage: /<command>